export const GET_ALL_LESSONS_REQUEST = 'GET_ALL_LESSONS_REQUEST' as const;
export const GET_ALL_LESSONS_SUCCESS = 'GET_ALL_LESSONS_SUCCESS' as const;
export const GET_ALL_LESSONS_ERROR = 'GET_ALL_LESSONS_ERROR' as const;

export const DELETE_LESSON_REQUEST = 'DELETE_LESSON_REQUEST' as const;
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS' as const;
export const DELETE_LESSON_ERROR = 'DELETE_LESSON_ERROR' as const;
